<?php

use Drupal\degov_common\Common;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_preprocess().
 */
function degov_node_press_preprocess(&$variables, $hook, &$info) {
  // Add template suggestions and libraries implemented in this module.
  Common::addThemeSuggestions($variables, $hook, $info, [
    'module_name' => 'degov_node_press',
    'entity_type' => 'node',
    'entity_bundles' => ['press'],
    'entity_view_modes' => ['teaser', 'latest', 'long_text', 'preview', 'slim', 'small_image']
  ]);
}

/**
 * Implements hook_views_pre_render().
 */
function degov_node_press_views_pre_render(ViewExecutable $view) {
  if (isset($view) && ($view->storage->id() == 'latest_press')) {
    $view->element['#attached']['library'][] = 'degov_node_press/slider';
  }
}