<?php

/**
 * Implements hook_preprocess_node().
 */
function degov_content_types_shared_fields_preprocess_node(&$variables) {
  /** @var \Drupal\node\NodeInterface $node */
  $node = $variables['node'];
  // Remove the right sidebar paragraph in case no content exists.
  if ($node->hasField('field_sidebar_right_paragraphs') && !empty($variables['content']['field_sidebar_right_paragraphs'])) {
    unset($variables['content']['field_sidebar_right_paragraphs']);
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function degov_content_types_shared_fields_preprocess_field(&$variables) {
  $field_name = $variables['field_name'];

  if (in_array($field_name, ['field_header_paragraphs', 'field_content_paragraphs'])) {
    $variables['items'][] = [
      'content' => [
        '#theme' => 'block_shariff',
        '#blocksettings' => [],
        '#attached' => array(
          'library' => array(
            'shariff/shariff',
          ),
        ),
      ],
    ];
  }
}