<?php

/**
 * Implements hook_preprocess_node().
 */
function degov_content_types_shared_fields_preprocess_node(&$variables) {
  /** @var \Drupal\node\NodeInterface $node */
  $node = $variables['node'];
  // Remove the right sidebar paragraph in case no content exists.
  if ($node->hasField('field_sidebar_right_paragraphs') && !empty($variables['content']['field_sidebar_right_paragraphs'])) {
    unset($variables['content']['field_sidebar_right_paragraphs']);
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function degov_content_types_shared_fields_preprocess_field(&$variables) {
  if (in_array($variables['field_name'], ['field_header_paragraphs', 'field_content_paragraphs'])) {
  }
}