<?php

use Drupal\degov_common\Common;
use Drupal\Core\Template\Attribute;

/**
 * Implements hook_preprocess().
 */
function degov_media_audio_preprocess(&$variables, $hook, &$info) {
  // Add template suggestions and libraries implemented in this module.
  Common::addThemeSuggestions($variables, $hook, $info, [
    'module_name' => 'degov_media_audio',
    'entity_type' => 'media',
    'entity_bundles' => ['audio'],
    'entity_view_modes' => ['usage'],
  ]);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function degov_media_audio_preprocess_media__audio(&$variables) {
  /* @var \Drupal\media_entity\Entity\Media $media */
  $media = $variables['media'];

  $variables['audio_attributes'] = new Attribute([
    'id' => 'audio-' . $media->id(),
    'controls' => 'controls',
  ]);

  /* @var \Drupal\file\Entity\File $file */
  $file = $media->field_audio_mp3->entity;
  if (!empty($file)) {
    $variables['audio_mp3'] = file_create_url($file->getFileUri());
  }

  $file = $media->field_audio_ogg->entity;
  if (!empty($file)) {
    $variables['audio_ogg'] = file_create_url($file->getFileUri());
  }
}