<?php

/**
 * @file
 * Contains degov_welcome.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function degov_welcome_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the degov_welcome module.
    case 'help.page.degov_welcome':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Welcome to deGov') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_block_view_alter().
 * Sets our own funbction to override the content of the
 * "powered by Drupal" block
 */
function degov_welcome_block_view_alter(array &$build, \Drupal\Core\Block\BlockPluginInterface $block) {
  if ($block->getBaseId() === 'system_powered_by_block') {
    $build['#pre_render'][] = 'degov_welcome_block_poweredby_prerender';
  }
}

/**
 * Implements hook_block_poweredby_prerender().
 * Override the content of the "powered by Drupal" block
 * @param $build
 *
 * @return array $build
 */
function degov_welcome_block_poweredby_prerender(array $build) {
  $build['content']['#markup'] = '<span>' . t('Powered by <a href=":poweredby">deGov</a>', array(':poweredby' => 'http://www.degov.org')) . '</span>';
  return $build;
}

/**
 * Implements hook_page_attachments_alter().
 * Overrides the "Generator" meta tag.
 */
function degov_welcome_page_attachments_alter(array &$attachments) {
// Change Generator META tag.
  foreach ($attachments['#attached']['html_head'] as $key => $attachment) {
    if (isset($attachment[1])) {
      if ($attachment[1] === 'system_meta_generator') {
        // The Element 0 contains all info.
        // The Element 1 contains the type of meta tag.
        $attachments['#attached']['html_head'][$key][0] = array(
          '#type'       => 'html_tag',
          '#tag'        => 'meta',
          '#attributes' => array(
            'name'    => 'Generator',
            'content' => 'deGov (https://www.degov.de)',
          ),
        );
      }
    }
  }
}

/**
 * Implements hook_css_alter().
 * Add a custom CSS file to fix image sizes in backend.
 */
function degov_welcome_css_alter(&$css, \Drupal\Core\Asset\AttachedAssetsInterface $assets) {
  
  $is_admin = \Drupal::service('router.admin_context')->isAdminRoute();
  if ($is_admin) {
    $css[drupal_get_path('module', 'degov_welcome') . '/css/admin.css'] = array(
      'weight' => 200.1,
      'group' => 0,
      'type' => 'file',
      'data' => drupal_get_path('module', 'degov_welcome') . '/css/admin.css',
      'version' => '8.2.2',
      'media' => 'all',
      'preprocess' => 1,
      'browsers' => array(
        'IE' => 1,
        '!IE' => 1,
      ),
    );
  }
}
