<?php

use Drupal\degov_common\Common;

/**
 * Implements hook_preprocess().
 */
function degov_paragraph_faq_preprocess(&$variables, $hook, &$info) {
  // Add template suggestions and libraries implemented in this module.
  Common::addThemeSuggestions($variables, $hook, $info, [
    'module_name' => 'degov_paragraph_faq',
    'entity_type' => 'paragraph',
    'entity_bundles' => ['faq', 'faq_list'],
    'entity_view_modes' => ['default', 'preview'],
  ]);
}
