<?php

/**
 * Implements hook_facets_search_api_query_type_mapping_alter().
 */
function degov_search_content_facets_search_api_query_type_mapping_alter($backend_plugin_id, array &$query_types) {
  $query_types['degov_date_range'] = 'search_api_degov_date_range';
}

/**
 * Implements hook_form_alter().
 */
function degov_search_content_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_press_edit_form') {
    $form_i = 'sadasdasd';
  }
}