<?php

/**
 * @file
 * ITNRW Map module
 *
 * Provides a ITNRW link/map formatter for simple Text fields. Note that
 * this is just a field formatter for Text fields, not a field. See README.txt
 * for more information.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function itnrw_map_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the itnrw_map module.
    case 'help.page.itnrw_map':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Settings of ITNRW Maps') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function itnrw_map_theme() {
  return array(
    'itnrw_map_output' => array(
      'variables' => array(
        'zoom' => NULL,
        'coordinates' => NULL,
      ),
      'template' => 'itnrw-map-output',
    ),
  );
}
