<?php

use Drupal\degov_content_types_shared_fields\Common;

/**
 * Implements hook_preprocess().
 */
function degov_media_tweet_preprocess(&$variables, $hook, &$info) {
  // Add template suggestions and libraries implemented in this module.
  Common::addThemeSuggestions($variables, $hook, $info, [
    'module_name' => 'degov_media_tweet',
    'entity_type' => 'media',
    'entity_bundles' => ['tweet'],
    'entity_view_modes' => [],
  ]);
}
