<?php

use Drupal\degov_common\Common;

/**
 * Implements hook_uninstall().
 */
function degov_media_address_uninstall() {
  // Removes all module type defined content when uninstalling the module.
  Common::removeContent([
    'entity_type' => 'media',
    'entity_bundles' => ['address'],
  ]);
}

/**
 * Enable the usage view mode.
 */
function degov_media_address_update_8001() {
  \Drupal::service('degov_config.updater')->configPartialImport('degov_media_address');
}
