<?php

use Drupal\degov_content_types_shared_fields\Common;

/**
 * Implements hook_preprocess().
 */
function degov_media_address_preprocess(&$variables, $hook, &$info) {
  // Add template suggestions and libraries implemented in this module.
  Common::addThemeSuggestions($variables, $hook, $info, [
    'module_name' => 'degov_media_address',
    'entity_type' => 'media',
    'entity_bundles' => ['address'],
    'entity_view_modes' => ['default_map', 'osm_map'],
  ]);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function degov_paragraph_map_preprocess_paragraph__map(&$variables) {
  // Pass map arguments for the rendered map through javascript.
  if ($variables['paragraph']->hasField('field_map_address_reference')
    && !$variables['paragraph']->get('field_map_address_reference')->isEmpty()) {
    $address_reference = $variables['paragraph']->get('field_map_address_reference')->entity;
    if (!empty($address_reference)) {
      $location = $address_reference->get('field_address_location');
      if (!$location->isEmpty()) {
        // Add latitude and longitude.
        $variables['#attached']['drupalSettings']['map']['lat'] = $location->lat;
        $variables['#attached']['drupalSettings']['map']['lon'] = $location->lon;
        // Add pin image location.
        $variables['#attached']['drupalSettings']['map']['pin'] = '/' . drupal_get_path('module', 'degov_media_address') . '/images/map-icon.png';
        // Override map rendering based on view mode selection.
        if (!empty($variables['content']['field_map_address_reference'][0]['#view_mode'])
          && !$variables['paragraph']->get('field_map_address_view_mode')->isEmpty()) {
          $variables['content']['field_map_address_reference'][0]['#view_mode'] = $variables['paragraph']->field_map_address_view_mode->value;
        }
      }
    }
  }
}