<?php

use Drupal\degov_content_types_shared_fields\Common;

/**
 * Implements hook_preprocess().
 */
function degov_rss_feed_preprocess(&$variables, $hook, &$info) {
  // Add template suggestions and libraries implemented in this module.
  Common::addThemeSuggestions($variables, $hook, $info, [
    'module_name' => 'degov_rss_feed',
    'entity_type' => 'views',
    'entity_bundles' => ['view_rss'],
    'entity_view_modes' => [],
  ]);
}
