<?php

use Drupal\degov_content_types_shared_fields\Common;

/**
 * Implements hook_preprocess().
 */
function degov_paragraph_header_preprocess(&$variables, $hook, &$info) {
  // Add template suggestions and libraries implemented in this module.
  Common::addThemeSuggestions($variables, $hook, $info, [
    'module_name' => 'degov_paragraph_header',
    'entity_type' => 'paragraph',
    'entity_bundles' => ['image_header'],
    'entity_view_modes' => [],
  ]);
}