<?php

use Drupal\degov_common\Common;

/**
 * Implements hook_preprocess().
 */
function degov_media_person_preprocess(&$variables, $hook, &$info) {
  if ($hook === 'media') {
    /* @var \Drupal\media_entity\Entity\Media $media */
    $media = $variables['elements']['#media'];
    $variables['media'] = $media;
  }

  // Add template suggestions and libraries implemented in this module.
  Common::addThemeSuggestions($variables, $hook, $info, [
    'module_name' => 'degov_media_person',
    'entity_type' => 'media',
    'entity_bundles' => ['person'],
    'entity_view_modes' => [],
  ]);
}
