<?php

use Drupal\degov_common\Common;

/**
 * Implements hook_preprocess().
 */
function degov_paragraph_media_reference_preprocess(&$variables, $hook, &$info) {
  // Add template suggestions and libraries implemented in this module.
  Common::addThemeSuggestions($variables, $hook, $info, [
    'module_name' => 'degov_paragraph_media_reference',
    'entity_type' => 'paragraph',
    'entity_bundles' => ['media_reference'],
    'entity_view_modes' => ['default', 'preview'],
  ]);
}

/**
 * Implements hook_modules_installed().
 * @param $modules
 */
function degov_paragraph_media_reference_modules_installed($modules) {
  if (in_array('degov_paragraph_media_reference', $modules)) {
    // Set target bundles.
    _degov_media_reference_bundle_list();
  }
}

/**
 * Update field reference target bundles.
 */
function _degov_media_reference_bundle_list() {
  $enabled_bundles = [];
  $media_types = \Drupal\media_entity\Entity\MediaBundle::loadMultiple();
  /** @var \Drupal\media_entity\Entity\MediaBundle $media_type */
  foreach ($media_types as $media_type) {
    $enabled_bundles[$media_type->id()] = $media_type->id();
  }
  if (!empty($enabled_bundles)) {
    // Load the configuration for node_reference field storage.
    $config = \Drupal::configFactory()
      ->getEditable('field.field.paragraph.media_reference.field_media_reference_media');
    $settings = $config->get('settings');
    $settings['handler_settings']['target_bundles'] = $enabled_bundles;
    $config->set('settings', $settings);
    $config->save(TRUE);
  } else {
    drupal_set_message(t('There are no media bundles available'), 'warning');
  }
}
