<?php

use Drupal\degov_content_types_shared_fields\Common;

/**
 * Implements hook_preprocess().
 */
function degov_html_mail_preprocess(&$variables, $hook, &$info) {
  // Add template suggestions and libraries implemented in this module.
  Common::addThemeSuggestions($variables, $hook, $info, [
    'module_name' => 'degov_html_mail',
    'entity_type' => 'swiftmailer',
    'entity_bundles' => [],
    'entity_view_modes' => [],
  ]);
}