<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\file\FileInterface;

/**
 * @file
 * Contains degov_demo.module..
 */

/**
 * Implements hook_help().
 */
function degov_demo_help($route_name, RouteMatchInterface $route_match) {

  switch ($route_name) {

    // Main module help for the degov_welcome module.
    case 'help.page.degov_demo':

      $output = '';
      return $output;

    default:

  }

}


function degov_demo_file_validate(FileInterface $file, $validators = array()) {

  $validators['file_validate_extensions'][] = 'docx pptx xlsx';

  // Call the validation functions specified by this function's caller.
  $errors = array();
  foreach ($validators as $function => $args) {
    if (function_exists($function)) {
      array_unshift($args, $file);
      $errors = array_merge($errors, call_user_func_array($function, $args));
    }
  }

  // Let other modules perform validation on the new file.
  return array_merge($errors, \Drupal::moduleHandler()->invokeAll('file_validate', array($file)));

}