<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\file\FileInterface;

/**
 * @file
 * Contains degov_demo.module..
 */

/**
 * Implements hook_help().
 */
function degov_demo_help($route_name, RouteMatchInterface $route_match) {

  switch ($route_name) {

    // Main module help for the degov_welcome module.
    case 'help.page.degov_demo':

      $output = '';
      return $output;

    default:

  }

}
