<?php

use Drupal\degov_content_types_shared_fields\Common;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_preprocess().
 */
function degov_node_faq_preprocess(&$variables, $hook, &$info) {
  // Add template suggestions and libraries implemented in this module.
  Common::addThemeSuggestions($variables, $hook, $info, [
    'module_name' => 'degov_node_faq',
    'entity_type' => 'node',
    'entity_bundles' => ['faq'],
    'entity_view_modes' => []
  ]);
}

/**
 * Implements hook_views_pre_render().
 */
function degov_node_faq_views_pre_render(ViewExecutable $view) {
  if (isset($view) && ($view->storage->id() == 'search_faq')) {
    $view->element['#attached']['library'][] = 'degov_node_faq/faq';
  }
}