<?php

/**
 * Implements hook_theme().
 */
function nrw_menu_theme($existing, $type, $theme, $path) {
  return [
    'nrw_menu_header' => [
      'variables' => [
        'menu_items' => [],
        'menu_extra' => NULL,
      ],
      'template' => 'nrw-menu-header',
    ],
    'nrw_menu_footer' => [
      'variables' => [
        'menu_items' => [],
      ],
      'template' => 'nrw-menu-footer',
    ],
  ];
}

/**
 * Proprocess page content to add menus
 * 
 * @param $variables
 */
function nrw_menu_preprocess_page(&$variables) {
  // get the simplify_menu service
  $menuTree = \Drupal::service('simplify_menu.menu_items');
  // get the menu items from main menu tree
  $menuItems = $menuTree->getMenuTree('main');
  // create the variables for page.html.twig template
  $variables['page_header_menu'] = [
    '#theme' => 'nrw_menu_header',
    '#menu_items' => $menuItems,
    '#menu_extra' => '',
  ];
  $variables['page_footer_menu'] = [
    '#theme' => 'nrw_menu_footer',
    '#menu_items' => $menuItems,
    '#menu_extra' => '',
  ];
  // add the library for adding expandable functionality
  $variables['#attached']['library'][] = 'nrw_menu/nrw_menu';
}