<?php

use Drupal\degov_content_types_shared_fields\Common;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_preprocess().
 */
function degov_node_event_preprocess(&$variables, $hook, &$info) {
  // Add template suggestions and libraries implemented in this module.
  Common::addThemeSuggestions($variables, $hook, $info, [
    'module_name' => 'degov_node_event',
    'entity_type' => 'node',
    'entity_bundles' => ['event'],
    'entity_view_modes' => ['teaser', 'latest', 'long_text', 'preview', 'slim', 'small_image']
  ]);
}

/**
 * Implements hook_views_pre_render().
 */
function degov_node_event_views_pre_render(ViewExecutable $view) {
  if ($view->storage->id() == "events" && $view->current_display == 'attachment_1') {
    $view->element['#attached']['library'][] = 'degov_node_event/degov_events';
  }
}

/**
 * Implements hook_views_pre_build().
 */
function degov_node_event_views_pre_build(ViewExecutable $view) {
  $view->usePager(TRUE);
}
