<?php

use Drupal\degov_common\Common;

/**
 * Set Monday as the first day of the week.
 */
function degov_node_event_update_8001() {
  \Drupal::config('system.date')->set('first_day', 1);
}

/**
 * Implements hook_uninstall().
 */
function degov_node_event_uninstall() {
  // Removes all module type defined content when uninstalling the module.
  Common::removeContent([
    'entity_type' => 'node',
    'entity_bundles' => ['event'],
  ]);
}
