<?php

use Drupal\degov_common\Common;
use Drupal\Core\Url;
/**
 * Implements hook_preprocess().
 */
function degov_paragraph_slideshow_preprocess(&$variables, $hook, &$info) {
  $variables['#attached']['library'][] = 'degov_paragraph_slideshow/slideshow';
  // Add template suggestions and libraries implemented in this module.
  Common::addThemeSuggestions($variables, $hook, $info, [
    'module_name' => 'degov_paragraph_slideshow',
    'entity_type' => 'paragraph',
    'entity_bundles' => ['slide', 'slideshow'],
    'entity_view_modes' => ['preview'],
  ]);
}

/**
 * Implements hook_preprocess_paragraph().
 */
function degov_paragraph_slideshow_preprocess_paragraph(&$variables) {
  $paragraph = $variables['paragraph'];
  // Add variables to the slideshow template file.
  if ($paragraph->getType() == 'slideshow') {
    // Add the variable slideshow_type.
    $variables['slideshow_type'] = $paragraph->field_slideshow_type->value;
  }
  // Add variables to the slideshow template file.
  if ($paragraph->getType() == 'slide') {
    // Add the variable slide_link.
    $variables['slide_link'] = FALSE;
    if ($paragraph->field_slide_link->uri) { 
      $url = Url::fromUri($paragraph->field_slide_link->uri);
      //var_dump($url);
      $variables['slide_link'] = $url;
    }
  }
}