<?php
use Drupal\Core\Form\FormStateInterface;
use Drupal\degov_search_media_manager\FormAlter;
use Drupal\media_entity\MediaInterface;

/**
 * Implements hook_form_alter().
 */
function degov_search_media_manager_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(FormAlter::class)
    ->formAlter($form, $form_state, $form_id);
}

/**
 * Implements hook_preprocess_media().
 */
function degov_search_media_manager_preprocess_media(&$variables) {
  $view_mode = $variables['elements']['#view_mode'];
  $media = $variables['media'];

  if ($view_mode === 'usage' && $media instanceof MediaInterface) {
    /* @var \Drupal\entity_reference_integrity\EntityReferenceDependencyManager $dependency_manager */
    $dependency_manager = \Drupal::service('entity_reference_integrity.dependency_manager');

    if ($dependency_manager->hasDependents($media)) {
      $referencing_entities = $dependency_manager->getDependentEntities($media);

      foreach ($referencing_entities as $entity_type_id => $entities) {
        $build[$entity_type_id]['list'] = [
          '#title' => reset($entities)->getEntityType()->getLabel(),
          '#theme' => 'item_list',
          '#items' => [],
        ];

        /* @var \Drupal\Core\Entity\EntityInterface $entity */
        foreach ($entities as $entity) {
          $build[$entity_type_id]['list']['#items'][] = $entity->hasLinkTemplate('canonical') ? $entity->toLink() : $entity->label();
        }
      }

      if (!empty($build)) {
        $variables['content']['usage'] = $build;
      }
    }
  }
}