<?php

use Drupal\content_types_shared_fields\Common;

/**
 * Implements hook_preprocess().
 */
function degov_node_normal_page_preprocess(&$variables, $hook, &$info) {
  // Add template suggestions and libraries implemented in this module.
  Common::addThemeSuggestions($variables, $hook, $info, [
    'module_name' => 'degov_node_normal_page',
    'entity_type' => 'node',
    'entity_bundles' => ['normal_page'],
    'entity_view_modes' => ['teaser']
  ]);
}
